server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 18
  #设置图片保存的路径
  servlet:
    # 应用的访问路径
    context-path: /


spring:
  application:
    # 用于指定这个微服务名称，也就是在注册中心显示的名称，其他微服务同个这个名称调用服务
    name: summer-seller-server
  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # nacos配置