server:
  #服务实例端口
  port: 9010
  #设置图片保存的路径
  servlet:
    # 应用的访问路径
    context-path: /
#
logging:
  io:
    swagger:
      models:
        parameters:
          AbstractSerializableParameter: error

## Spring
spring:
  #循环依赖
  main.allow-circular-references: true

  profiles:
    # 环境配置
    active: dev
  application:
    # 应用名称
    name: oath-server
  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**

# mybatis-plus相关配置
mybatis-plus:
  #实体位置
  type-aliases-package: com.summer.oath.domain # 注意修改
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  # 注意路径
  mapper-locations: classpath:mapper/**.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 懒加载
    aggressive-lazy-loading: true
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    #map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    org.springframework.boot.autoconfigure: DEBUG

